### PR TITLE
Use the wabt crate

### LINKED ISSUE #270: Use the wabt crate
Currently running the in-tree wasm tests requires the `wat2wasm` command be installed. There's now a [wabt crate](https://crates.io/crates/wabt), so we should switch to using that, with an explicit dependency, instead.

### PR DESCRIPTION
**Pull request by pepyakin**
Fixes #270 

I'm not sure about adding wabt in cton-util since it'll make cton-util transitively dependent on C/C++ compiler.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Hmm, that's a good point.

Thinking about this some more, for the tests in the tree, maybe we should just check the .wasm files into the repo. That way we won't need a C++ compiler or a wabt install just to run the tests.

However, it would still be convenient for development to have `cton-util wasm` be able to read .wat files directly. So, what if we made the `wabt-rs` code here a [feature](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section) with an optional dependency?

**Comment by pepyakin** [comment]
> However, it would still be convenient for development to have cton-util wasm be able to read .wat files directly. So, what if we made the wabt-rs code here a feature with an optional dependency?

Opt-in or opt-out? I'm not sure, since they both have pros and cons.

**Comment by sunfishcode** [comment]
How about opt-in? I see the pros and cons, so maybe the thing that decides it is that not everyone using Cretonne is doing so with wasm. And not everyone doing so with wasm is using the in-tree implementation of `FuncEnvironment`, which is a significant part of what's being tested by those tests.

**Comment by quadrupleslap** [comment]
Here's a version where the entire wasm subcommand is opt-out:

https://github.com/quadrupleslap-forks-things/cretonne/tree/use-wabt

**Comment by sunfishcode** [comment]
@quadrupleslap I hadn't thought of making the whole wasm subcommand opt-out, but at first glance it seems to work out well. Would you mind submitting a new PR?

Eventually, once the APIs stablize more, we may end up splitting cretonne-wasm out into its own repo, but for now it's convenient to keep them together because they're still evolving together (eg. https://github.com/cretonne/cretonne/pull/346).

**Comment by pepyakin** [comment]
@quadrupleslap Thanks for working on this! 

Sorry about that this slipped from my radars : <

**Pull request closed without merging**
