### PR TITLE
document that low bitsize integers don't have complete arithmetic support

### PR DESCRIPTION
**Pull request by TyOverby**
I couldn't figure out how to get docs on the arithmetic functions, but I got it on the type!

### CODE REVIEW

**Comment by TyOverby** [comment]
closes https://github.com/cretonne/cretonne/issues/292

**Comment by TyOverby** [comment]
Gaah, I really should add that to my global git ignore.  Thanks @phase!

**Comment by sunfishcode** [comment]
#292 was fixed by #299, which it seems didn't get closed, however your patch here also adds text on the same lines as the types, which seems nice to have in addition, so I think it'd be good to merge too.

Could you update this PR to remove the spurious file, and fix the 80-column line so that pyflake is happy? Thanks!

**Comment by TyOverby** [comment]
Done (I think)

**Comment by sunfishcode** [comment]
These new failures are due to changes on the CI machine; see https://github.com/cretonne/cretonne/issues/323 for details. https://github.com/cretonne/cretonne/pull/321 should land with a fix soon.

**Comment by sunfishcode** [comment]
Looks good; thanks!

**Pull request merged**
